import evraz from './icons/evraz.svg';
import exhauster from './images/example.jpg';
import arrow from './icons/arrow.svg';
import mark from './icons/mark.svg';
import file from './icons/file.svg';
import scheme from './images/exhauster.svg';
import exhausterLink from './icons/arrowLink.svg';
import radio from './icons/radio.svg';
import thermometer from './icons/thermometer.svg';
import water from './icons/water.svg';

export const Exhauster = exhauster;
export const EvrazIcon = evraz;
export const ArrowIcon = arrow;
export const MarkIcon = mark;
export const FileIcon = file;
export const Scheme = scheme;
export const ExhausterLinkIcon = exhausterLink;
export const RadioIcon = radio;
export const ThermometerIcon = thermometer;
export const WaterIcon = water;
